bits 32
default rel

%include "std_string.asm"
%include "stdio.asm"
%include "std.asm"

section .data
	sep defString{", "}

	smsg dd 15
	msg db "Hello, World!", 0xd, 0xa,0



	foo defString{"Foo "}

	bar defString{"Bar", 0xd, 0xa}

	def_ext dd 0

	%macro MachineSlotEntry 3
		;.nameptr:	0
		dd %1
		;.price:	4
		dd %2
		;.maxcount:	8
		dd %3
		;.count:	12
		dd %3
	%endmacro
	
	machine_slot_x_address defString{"1234"}
	machine_slot_y_address defString{"abcd"}
	machine_slots_names:
		.oreo: rawDefString{"Oreo"}
		.pringles: rawDefString{"Pringles"}
		.mars: rawDefString{"Mars"}
		.gbread: rawDefString{"Green bread"}
	machine_slots:
	MachineSlotEntry machine_slots_names.oreo, 200, 1
	MachineSlotEntry machine_slots_names.pringles, 250, 1

	MachineSlotEntry machine_slots_names.mars, 100, 1
	MachineSlotEntry machine_slots_names.gbread, 2999, 1

	console_input_key_event:	;18
		.type:
			dw 0	;	Should be 0x0001 for key event
			dw 0	;	Padding cuz the event union appears to have an alignment of 4
		.keydown:
			dd 0	;	bool
		.repeat:
			dw 0 	;	Number of times this key has been pressed
		.keycode:
			dw 0	;	https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
		.scancode:
			dw 0	;	keyboard generated scan code. Device dependant. Ignore
		.char:
			dw 0	;	Ascii/WideChar character generated by the key press. for ascii only 1 byte is used
		.control_keys:
			dd 0	;	Control Keys pressed with this key.
	dd 0	;	Padding
	dd 0	;	Padding
	console_input_key_event_count:
		dd 0	;	Garbage?

section .text
extern _ReadConsoleInputA@16

global main

do_keypad:
	push eax
	push edx
	push ecx
	enter 4, 0		;	0-EventCountRead

.get_inp:
	;getString eax, "Step A", endl
	;call cout

	push console_input_key_event_count
	push dword 1
	push console_input_key_event
	push dword [stdin]
	call _ReadConsoleInputA@16

	mov edx, eax
	call tryhandleerror

	;push eax
	;getString eax, "Step B", endl
	;call cout
	;pop eax
	

	getString eax, "Input Event "
	call snew

	;call sappend_int
	;call sappend_endl

	xor edx, edx
	mov dx, word [console_input_key_event.type]
	call sappend_int
	call sappend_endl
	call cout
	call mfree
	cmp dx, 0x0001
	jne .get_inp

.kev_process:
	mov eax, dword [console_input_key_event.keydown]
	add eax, eax
	jz .get_inp	;If key up then repeat

	getString eax, "Key Down '#' code: "
	call snew

	mov cx, word [console_input_key_event.char]

	mov edx, eax
	add edx, 14
	mov byte [edx], cl

	xor edx, edx
	mov dx, word [console_input_key_event.keycode]
	call sappend_int
	call sappend_endl
	call cout
	call mfree
	jmp .get_inp
.exit:
	leave
	pop ecx
	pop edx
	pop eax
	ret


sappend_price:	;	Appends the price in EDX to the string in EAX. Both EDX and EAX remain unchanged
	push ebx
	push ecx
	push edx

	mov ebx, edx
	
	mov ecx, 100
	DIVMOD ebx, ecx, ecx

	getString edx, 156
	call sappend

	mov edx, ebx
	call sappend_int

	mov edx, ecx
	add edx, 100
	call sappend_int

	mov edx, eax
	add edx, dword [eax]
	add edx, 1
	mov byte [edx], '.' 

	pop edx
	pop ecx
	pop ebx
	ret

testallansi:
	getString eax, "ANSI Test"
	call snew
	call cout
	mov edx, 0
.loop:
	mov dword [eax], 0
	call sappend_int
	
	push edx
	getString edx, " = w"
	call sappend
	pop edx

	mov ecx, eax
	add ecx, dword [eax]
	add ecx, 3
	mov byte [ecx], dl
	call sappend_endl
	call cout
	inc dx
	cmp dl, 0
	jne .loop
	call mfree
	getString eax, "Test"
	ret



main:

	call __init__


	mov eax, smsg
	call cout

	getString eax, "Test 1", endl, "Test 2", endl
	call cout
										;	The real program starts

	;mov eax, 0
	getString eax, "The char of the day is '"
	call snew
	mov dl, 'E'
	call sappend_char
	mov dl, "'"
	call sappend_char
	call sappend_endl
	call cout
	call mfree

	sub ebx, esp

	call do_keypad		;	INPUT TEST

	getString eax, "Stack offset: "
	call snew
	mov edx, ebx
	call sappend_int
	call sappend_endl
	call cout

	mov eax, smsg

	call snew
	call cout

	mov eax, foo
	call snew

	mov edx, bar
	call sappend

	mov edx, foo
	call sappend

	mov edx, -1234
	call sappend_int
	call sappend_endl

	call cout

										;	Sample fibonacci sequence (up to 99999)
	mov ecx, 0
	mov ebx, 1
	mov edx, 1

.fib_loop:
	mov dword [eax], 0		;	Clear the string
	push edx
	mov edx, ebx
	inc ebx
	call sappend_int
	getString edx, "	=> "
	call sappend
	pop edx
	call sappend_int
	call sappend_endl
	call cout

	mov edi, edx
	mov edx, ecx
	mov ecx, edi
	add edx, ecx

	cmp edx,  999999999
	jl .fib_loop

	call mfree

	getString eax, "Input some text: "
	call cout

	mov eax, 0
	call snew

	mov edx, 0
	call cin			

	mov edx, eax
	push edx
	getString eax, endl, "You typed in: "
	call snew
	call sappend
	call sappend_endl
	call cout
	
	pop edx
	push edx
	getString eax, "It is "
	call snew
	mov edx, [edx]
	call sappend_int
	getString edx, " bytes long.", endl
	call sappend
	call cout
	

	pop edx

	mov al, 'a'
	call sfind_char
	cmp eax, dword -1

	je .notfound
.found:
	mov edx, eax
	getString eax, "There is an 'a' in the string at position "
	call snew
	call sappend_int
	call sappend_endl
	call cout
	jmp .fexit
.notfound:
	getString eax, "There is no 'a' in this string.", endl
	call cout
.fexit:

	getString eax, "Test: "
	call snew
	mov edx, 90100

	call sappend_price
	call cout

	;call testallansi	;	Display all ANSI characters and their codes

	;Return a successfull exit code and exit
	push dword 0;123456789
	call _ExitProcess@4